### ISSUE TITLE
大神，Fresco貌似不支持循环播放animated WebP

### ISSUE THREAD

**Issue by Bertkiing** [TinoGuo/AnimatedWebp2#1]
开发中，有需要用到循环播放animated WebP的需求，大神给提供一下思路

**Comment by TinoGuo** [comment]
@Bertkiing 是需要播放的webp本身是循环的，还是一张单次循环webP想循环？

**Comment by TinoGuo** [comment]
没有回复，我要关闭这个issue了

**Comment by Bertkiing** [comment]
对不住，太忙了都忘了这个啦，是想单次循环一张webP

**Comment by TinoGuo** [comment]
@Bertkiing 1.4之前和之后有两种实现方法，1.4之前直接获取Animator控制，1.4之后可以参考这个issue

**Comment by Bertkiing** [comment]
@TinoGuo 哪个issue啊？

**Comment by TinoGuo** [comment]
@Bertkiing https://github.com/facebook/fresco/issues/1900参看这个issue
